# Generated by Django 5.0.6 on 2024-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_card', models.CharField(max_length=200)),
                ('accessed_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_abnormal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recommadtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommadtion', models.TextField(default='empty')),
                ('education', models.TextField(default='empty')),
            ],
        ),
    ]
