# Generated by Django 5.0.6 on 2024-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WardAdmissionDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('discharged_by', models.CharField(max_length=100)),
                ('discharged_from_hospital', models.BooleanField(default=False)),
                ('discharge_remark', models.TextField()),
                ('discharge_date', models.DateTimeField()),
                ('appointment', models.CharField(max_length=100)),
            ],
        ),
    ]
