# Generated by Django 5.0.6 on 2024-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('health_provider_name', models.CharField(max_length=50)),
                ('pharmacist_name', models.CharField(max_length=50)),
                ('drug_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('full_order_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
